### ISSUE TITLE
Deploy config in Eclipse

### ISSUE THREAD

**Issue by voicevon** [adamgreen/gcc4mbed#55]
The original description is
The string you use for Value: will depend on what commands are required to copy binaries to the mbed device in your environment. Here are some examples that I use on various operating systems that I test with (please note that the GCC4MBED build system will automatically replace the PROJECT string with the name of your project, FileTest in this case):
OS X: cp PROJECT.bin /Volumes/MBED/ ; sync
Linux: cp PROJECT.bin /media/MBED/ ; sync
Windows: **_copy PROJECT.bin e:\_**

I got this
**_Deploying to target.
The system cannot find the file specified.
make: *** [LPC1768-deploy] Error 1_**

I change the string to   _**copy LPC1768\FileTest.bin e:\**_
Then got the correct response as
**_Deploying to target.
        1 file(s) copied._**
 I only tested it on Windows platform only ,but had tested it  many times.Adam,Please update it.

**Comment by adamgreen** [comment]
The current GCC4MBED_DEPLOY settings listed in the documentation are correct and work with the command line version of gcc4mbed. You shouldn't need to hardcode the names like you have shown above. You are hitting some other issue.

Since no one who uses Eclipse appears to want to keep these documents up to date, I will probably just remove them since I am not in a position to keep them current.
